USE [master]
GO

/****** Object:  Database [Helperland]    Script Date: 20-02-2022 05:53:18 PM ******/
CREATE DATABASE [Helperland]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Helperland', FILENAME = N'F:\New folder\MSSQL15.MSSQLSERVER\MSSQL\DATA\Helperland.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Helperland_log', FILENAME = N'F:\New folder\MSSQL15.MSSQLSERVER\MSSQL\DATA\Helperland_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Helperland].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Helperland] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Helperland] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Helperland] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Helperland] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Helperland] SET ARITHABORT OFF 
GO

ALTER DATABASE [Helperland] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Helperland] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Helperland] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Helperland] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Helperland] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Helperland] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Helperland] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Helperland] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Helperland] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Helperland] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Helperland] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Helperland] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Helperland] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Helperland] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Helperland] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Helperland] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Helperland] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Helperland] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Helperland] SET  MULTI_USER 
GO

ALTER DATABASE [Helperland] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Helperland] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Helperland] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Helperland] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Helperland] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Helperland] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Helperland] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Helperland] SET  READ_WRITE 
GO


